icons = "awesome"

[theme]
name = "solarized-dark"

[theme.overrides]
separator = "<span font='15'></span>"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
show_percentage = true

[[block]]
block = "xrandr"
icons = true
resolution = true
interval = 2

[[block]]
block = "pacman"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
format = "{utilization}% {barchart} {frequency}GHz"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "uptime"

[[block]]
block = "temperature"
collapsed = true
format = "{max}° max, {average}° avg"
chip = "*-isa-*"

[[block]]
block = "net"
device = "wlp59s0"
ssid = false
signal_strength = true
ip = true
graph_down = true
speed_up = true
speed_down = false
interval = 1

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
interval = 60
